before:
  hooks:
    - go mod tidy

builds:
  - id: policy-reports
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: policy-reports
    flags:
      - -trimpath
    # ldflags:
    #   - -s -w -X github.com/kyverno/policy-reports/pkg/version.BuildVersion={{ .Version }}

kos:
  - build: policy-reports
    repository: ghcr.io/kyverno/policy-reports
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}' 
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
      - --yes
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - ${artifact}
      - --yes

# brews:
#   - homepage: https://kyverno.github.io/policy-reports
#     description: Declarative Kubernetes end-to-end testing.
#     repository:
#       owner: kyverno
#       name: policy-reports
#       branch: brew-{{.Version}}
#       pull_request:
#         enabled: true
#         base:
#           owner: kyverno
#           name: policy-reports
#           branch: main

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  name_template: '{{ incpatch .Version }}-next'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
