apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha2.wgpolicyk8s.io
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "policy-reports.labels" . | nindent 4 }}
spec:
  group: wgpolicyk8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ include "policy-reports.fullname" . }}
    namespace: {{ $.Release.Namespace }}
  version: v1alpha2
  versionPriority: 100
