apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
metadata:
  name: {{ include "reports-server.fullname" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
    {{- include "reports-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  - clusterpolicyreports
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "reports-server.fullname" . }}
  labels:
    {{- include "reports-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "reports-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "reports-server.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
