apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  labels:
    pv.beta.kubernetes.io/gid: "2000"
spec:
  selector:
    matchLabels:
    {{- include "reports-server.selectorLabels" . | nindent 4 }}
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
