# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ArtifactHub Lint

permissions: {}

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    container:
      image: artifacthub/ah
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run ah lint
        working-directory: ./charts/
        run: |
          set -e
          ah lint
