# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ArtifactHub Lint

permissions: {}

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    container:
      image: artifacthub/ah
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run ah lint
        working-directory: ./charts/
        run: |
          set -e
          ah lint
