# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Helm install

permissions: {}

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Create cluster
        run: |
          set -e
          make kind-create
      - name: Install chart
        run: |
          set -e
          make kind-install
